[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
an_test = "BuvS4T7L1kFGRiQXiKD76khfLUxq9EqyeX3nH3CEYPPK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/akinobu.ono/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
